/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["AuthCallbackCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Link */
        get: operations["AuthLinkLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["AuthLoginLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["AuthLogoutLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["AuthMeMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}/alliances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AddAllianceAccess */
        post: operations["MapsMapIdAlliancesAddAllianceAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}/corporations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AddCorporationAccess */
        post: operations["MapsMapIdCorporationsAddCorporationAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AddUserAccess */
        post: operations["MapsMapIdUsersAddUserAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CreateMap */
        post: operations["MapsCreateMap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LoadMap */
        get: operations["MapsMapIdLoadMap"];
        put?: never;
        post?: never;
        /** DeleteMap */
        delete: operations["MapsMapIdDeleteMap"];
        options?: never;
        head?: never;
        /** UpdateMap */
        patch: operations["MapsMapIdUpdateMap"];
        trace?: never;
    };
    "/maps/alliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ListAlliance */
        get: operations["MapsAllianceListAlliance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/corporation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ListCorporation */
        get: operations["MapsCorporationListCorporation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/owned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ListOwned */
        get: operations["MapsOwnedListOwned"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/shared": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ListShared */
        get: operations["MapsSharedListShared"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}/alliances/{alliance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** RemoveAllianceAccess */
        delete: operations["MapsMapIdAlliancesAllianceIdRemoveAllianceAccess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}/corporations/{corporation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** RemoveCorporationAccess */
        delete: operations["MapsMapIdCorporationsCorporationIdRemoveCorporationAccess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** RemoveUserAccess */
        delete: operations["MapsMapIdUsersUserIdRemoveUserAccess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GetCharacter */
        get: operations["UsersCharactersCharacterIdGetCharacter"];
        put?: never;
        post?: never;
        /** DeleteCharacter */
        delete: operations["UsersCharactersCharacterIdDeleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/characters/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LinkCharacter */
        get: operations["UsersCharactersLinkLinkCharacter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ListCharacters */
        get: operations["UsersCharactersListCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddAllianceAccessRequest */
        AddAllianceAccessRequest: {
            alliance_id: number;
            /** @default viewer */
            role: string;
        };
        /** AddCorporationAccessRequest */
        AddCorporationAccessRequest: {
            corporation_id: number;
            /** @default viewer */
            role: string;
        };
        /** AddUserAccessRequest */
        AddUserAccessRequest: {
            /** Format: uuid */
            user_id: string;
            /** @default viewer */
            role: string;
        };
        /** CharacterListResponse */
        CharacterListResponse: {
            characters: components["schemas"]["users_service_CharacterInfo"][];
        };
        /** CreateMapRequest */
        CreateMapRequest: {
            name: string;
            description?: string | null;
            /** @default false */
            is_public: boolean;
        };
        /** EnrichedLinkInfo */
        EnrichedLinkInfo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            source_node_id: string;
            /** Format: uuid */
            target_node_id: string;
            wormhole_code?: string | null;
            wormhole_mass_total?: number | null;
            wormhole_mass_jump_max?: number | null;
            wormhole_mass_regen?: number | null;
            wormhole_lifetime?: number | null;
            wormhole_is_static?: boolean | null;
            lifetime_status: string;
            /** Format: date-time */
            date_lifetime_updated: string;
            mass_usage: string;
            /** Format: date-time */
            date_mass_updated: string;
        };
        /** EnrichedNodeInfoResponse */
        EnrichedNodeInfoResponse: {
            /** Format: uuid */
            id: string;
            pos_x: number;
            pos_y: number;
            system_id: number;
            system_name: string;
            constellation_id?: number | null;
            constellation_name?: string | null;
            region_id?: number | null;
            region_name?: string | null;
            security_status?: number | null;
            security_class?: string | null;
            wh_class?: number | null;
            wh_effect_name?: string | null;
            wh_effect_buffs?: Record<string, never>[] | null;
            wh_effect_debuffs?: Record<string, never>[] | null;
        };
        /** MapDetailResponse */
        MapDetailResponse: {
            map: components["schemas"]["MapInfo"];
            nodes: components["schemas"]["EnrichedNodeInfoResponse"][];
            links: components["schemas"]["EnrichedLinkInfo"][];
        };
        /** MapInfo */
        MapInfo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            name: string;
            description?: string | null;
            is_public: boolean;
            /** Format: date-time */
            date_created: string;
            /** Format: date-time */
            date_updated: string;
        };
        /** MapListResponse */
        MapListResponse: {
            maps: components["schemas"]["MapInfo"][];
        };
        /** UpdateMapRequest */
        UpdateMapRequest: {
            name?: string | null;
            description?: string | null;
            is_public?: boolean | null;
        };
        /** UserInfo */
        UserInfo: {
            /** Format: uuid */
            id: string;
            characters: components["schemas"]["auth_service_CharacterInfo"][];
        };
        /** CharacterInfo */
        auth_service_CharacterInfo: {
            id: number;
            name: string;
            corporation_id?: number | null;
            alliance_id?: number | null;
        };
        /** CharacterInfo */
        users_service_CharacterInfo: {
            id: number;
            name: string;
            corporation_id?: number | null;
            alliance_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthCallbackCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect Response */
            200: {
                headers: {
                    /** @description target path for the redirect */
                    location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    AuthLinkLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect Response */
            200: {
                headers: {
                    /** @description target path for the redirect */
                    location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthLoginLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect Response */
            200: {
                headers: {
                    /** @description target path for the redirect */
                    location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthLogoutLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    AuthMeMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    MapsMapIdAlliancesAddAllianceAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAllianceAccessRequest"];
            };
        };
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsMapIdCorporationsAddCorporationAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCorporationAccessRequest"];
            };
        };
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsMapIdUsersAddUserAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddUserAccessRequest"];
            };
        };
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsCreateMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMapRequest"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapInfo"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsMapIdLoadMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapDetailResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsMapIdDeleteMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsMapIdUpdateMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMapRequest"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapInfo"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsAllianceListAlliance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapListResponse"];
                };
            };
        };
    };
    MapsCorporationListCorporation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapListResponse"];
                };
            };
        };
    };
    MapsOwnedListOwned: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapListResponse"];
                };
            };
        };
    };
    MapsSharedListShared: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapListResponse"];
                };
            };
        };
    };
    MapsMapIdAlliancesAllianceIdRemoveAllianceAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
                alliance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsMapIdCorporationsCorporationIdRemoveCorporationAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    MapsMapIdUsersUserIdRemoveUserAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    UsersCharactersCharacterIdGetCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["users_service_CharacterInfo"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    UsersCharactersCharacterIdDeleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    UsersCharactersLinkLinkCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect Response */
            200: {
                headers: {
                    /** @description target path for the redirect */
                    location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersCharactersListCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterListResponse"];
                };
            };
        };
    };
}
